### ISSUE TITLE
Direct Play

### ISSUE THREAD

**Issue by Montellese** [Montellese/mediaimporter.plex#12]
Support playing media files directly accessible to Kodi (e.g. on a local NAS) without going through the PMS.

This should be configurable i.e. the user should be able to choose on a media provider level whether Direct Play should be used or not.

**Comment by JeordyR** [comment]
Were you thinking of this as forcing a "direct play" through plex, or avoiding playback through plex all-together? Plex's definition of these is a bit different then Kodi I think:

Direct Play: Stream the file without any modification
Direct Stream: Stream the file while repackaging the container but keeping the internal formats
Transcode: Stream the file and transcode the internal video and/or audio formats

I have a branch where I've gotten the latter working:
https://github.com/JeordyR/mediaimporter.plex/tree/feature/direct_play

Replaces the 'path' field with a path to the item locally so playback avoids plex entirely. Also have some settings to allow path replacement for flexibility.

On my setup for instance, my PMS local pathing is `/data/<library>`, but accessing this from a client over samba ends up being `smb://NASIP/storage/media/<library>` so I have replacement settings swap /data for smb://NASIP/storage/media

If that matches what you're looking for, I'll do a PR after the delta_sync one goes through so I can get it rebased and clean up the history a bit better before starting the review.

**Comment by Montellese** [comment]
In `mediaimporter.emby` there is a setting for users to choose whether they want to use `Direct Play` or `Direct Stream` where the former uses the actual path on the filesystem and the latter uses HTTP streaming. There is also some logic that transforms windows UNC paths into Kodi's `smb://` paths but nothing for other paths. Obviously this only works if the user has setup Kodi to be able to access the media using the same paths (directly, through path substitution, ...).

**Comment by enen92** [comment]
If you look at the mediaimporter.emby implementation you'll easily find what the feature is - pipe the direct path to the media item to Kodi instead of having to go through the Plex server. Last time I looked into it, it was pretty easy to implement (you can get the path from plexapi providing the id).

Thanks for picking and working on this add-on. This is a much wanted feature in Kodi 👍

**Comment by JeordyR** [comment]
Good deal, sounds like we are on the same page. I have that setup currently working in this branch of my fork: https://github.com/JeordyR/mediaimporter.plex/tree/feature/direct_play

I'll get a PR in once the direct_play PR finishes up.
