### ISSUE TITLE
Skip Intro Feature

### ISSUE THREAD

**Issue by JeordyR** [Montellese/mediaimporter.plex#24]
Plex recently added a feature that does analysis on Episode video files to find and store the start/stop time of "intros" and exposes a Skip Intro button in their players to allow users to skip past those detected intros.

https://support.plex.tv/articles/skip-content/

The start/stop time of intros is available in the Plex api and the python plexapi package has already [added support for them](https://github.com/pkkid/python-plexapi/pull/498/files).

Very cool feature that would be great to bring into Kodi. Not sure if this feature really fits within this addon or if it belongs more as its own. Figured I'd bring it up in here and see what you guys thought of implementing it within this addon or not.

Also found an abandoned addon that started implementing this type of thing in Kodi natively that shows the implementation on the player side:
https://github.com/aenemapy/aenemapyrepo/blob/master/script.tvskipintro/service.py

**Comment by Montellese** [comment]
How does this work exactly? Is there a way to pass this information when starting the stream? Or does it have to be manually triggered as soon as the intro starts? Is it simply a marker telling the client that it can jump to a specific time to skip past the intro?

If it has to be integrated into the player's OSD this might be tricky because I don't think that Kodi already supports something like that from add-ons.

**Comment by Long-Man** [comment]
The Prime addon has a similar feature. It is some kind of dialog that appears as soon as the episode starts. You can enter/ok to skip the intro or wait and the dialog goes away just before the intro is finished

**Comment by JeordyR** [comment]
> How does this work exactly? Is there a way to pass this information when starting the stream? Or does it have to be manually triggered as soon as the intro starts? Is it simply a marker telling the client that it can jump to a specific time to skip past the intro?
> 
> If it has to be integrated into the player's OSD this might be tricky because I don't think that Kodi already supports something like that from add-ons.

Basically we just pull timestamps from plex (start of intro playback time, end of intro playback time), it doesn't have any native support for doing it via the stream or anything.

In the abandoned addon I linked it looks like they just hooked into the player and watched the playback time. If the skip timestamps are present, cause a button to pop-up when hitting the 'start' of the intro time, clicking will skip the video to the 'end' of the intro, then remove the button. 

This is also how the official plex client works. "Skip Intro" button pops up at the top-right of the screen with focus, clicking it jumps to 1 second before the end of the intro then goes away. Or the button goes away after getting to the end fo the intro if it was not clicked.

Seems like this would potentially fit into plex/player.py, but I'm not sure what the best way would be to hook in and constantly watch the playback time without disrupting the other actions. Maybe a check in _startPlayback for if we have the intro details, if so spin up another process to watch playback time and handle the button and action?

**Comment by Long-Man** [comment]
https://github.com/Sandmann79/xbmc/blob/da41ff361b50d0de02b4f6e5322c1d4a1005a4bf/plugin.video.amazon-test/resources/lib/playback.py#L689

**Comment by Noustaa** [comment]
Hey guys, just for info, Composite support the skip intro feature with Plex (Plex pass required of course) https://github.com/anxdpanic/plugin.video.composite_for_plex

I hope that it could help you find a solution to support it.
Thank you for your work !

**Comment by Montellese** [comment]
@JeordyR would you be able / willing to test a version of the Plex media importer add-on which supports skipping intros? It requires updating the `python-plexapi` which was a bit tricky but I think I've figured it out now. In the settings of the tvshow media import of a Plex media provider there's a new `Playback` category where you can choose between the following "skip intro" options:
* never: skip intro markers provided by Plex are ignored
* ask: as soon as video playback reaches the detected intro a `Skip Intro` button is shown which can either be selected or closed.
* always: as soon as the video playback reaches the detected intro playback jumps forward to the end of the detected intro

@Noustaa thanks for your input. It was very valuable especially the dialog / button / skin integration which I've never done before.
