### ISSUE TITLE
No sync

### ISSUE THREAD

**Issue by rijsab** [Montellese/mediaimporter.plex#28]
I connect through Myplex to the server and after testing the connection everything works good. However there is no sync happening at all, even if I mannually force to sync. I habe added both Movies as TV Shows. 

The server is connected by https://

**Comment by Montellese** [comment]
Please provide a debug log from Kodi while trying to sync at least one of the imports. Thanks.

**Comment by rijsab** [comment]
Here you go pal

**Comment by Montellese** [comment]
Thanks. You need to open the settings of your imports (movies and tvshows) and explicitely choose which library sections from your PMS should be imported.

Please let me know if that fixes the issue for you. Maybe I should change this to importing all library sections by default...

**Comment by rijsab** [comment]
> Thanks. You need to open the settings of your imports (movies and tvshows) and explicitely choose which library sections from your PMS should be imported.
> 
> Please let me know if that fixes the issue for you. Maybe I should change this to importing all library sections by default...

Not sure what you mean by opening the settings of the library. Where should I open this? If I open TV shows I see the setting menu with tw0 options at the left. One of them is the library section.. when I hit this it shows me an empty page and nothing to choose from. If I hit sync manually nothing happens either.. would be great if I could get a step by step guidance..

Cheers for the support, much appreciated!

**Comment by rijsab** [comment]
Just FYI - I am using this on Rasp Pi 4 with LibreElec as OS.

**Comment by Montellese** [comment]
> Not sure what you mean by opening the settings of the library. Where should I open this? If I open TV shows I see the setting menu with tw0 options at the left. One of them is the library section.. when I hit this it shows me an empty page and nothing to choose from. If I hit sync manually nothing happens either.. would be great if I could get a step by step guidance..

Yeah you need to open the info / settings dialog for the specific media import (e.g. "Movies" or "TV shows") and choose one of the library sections from your PMS.

For me it looks like this:
![image](https://user-images.githubusercontent.com/75864/121850921-c6d38b00-cced-11eb-9dbd-9748e0976daf.png)

and then I get the following list of movie library sections from my PMS:
![image](https://user-images.githubusercontent.com/75864/121850957-d652d400-cced-11eb-8c19-a065c6f48dda.png)

Ignore the "Playback" category. This has been added after the last release of `mediaimporter.plex` and will be available in the next version.

**Comment by rijsab** [comment]
Thanks - I did this however when choosing the library nothing happens, so I dont see anything in the 2nd step you have mentioned (i.e. movies & test movies).

My brother is sharing his Plex library with movies & TV Shows through a https://.. I usr a Pi 4 with OSMC and tried also LibreElec. Everything connects really well but cannot get to the second step and therefor no sync happening at all.

**Comment by Montellese** [comment]
Do you use the library sharing feature provided by Plex or do you simply connect to your brother's PMS? I have access to a PMS from a friend and there everything works fine but I'm not sure how he setup sharing. Maybe there's a case which I haven't encountered yet which results in you not seeing the shared library sections.

**Comment by rijsab** [comment]
Not sure what you mean by this pal. Everything is managed in Plex. When I connect I have to sign in with 4 digits for Plex Activation. I have a Plex account and my brother invited me for sharing. In Plex native app everything works fine. I have also tried PlexKodiConnect and also there all libraries are showing up and synced.

**Comment by Montellese** [comment]
This is what the sharing view looks like for me:
![20210614_plex_sharing](https://user-images.githubusercontent.com/75864/121861106-d48f0d80-ccf9-11eb-8f55-8499a525ea97.png)

The last user shares two servers with me and each server has multiple library sections. When I manually add a media provider using `mediaimporter.plex` I can see my own server and the two servers from my friend. I then select one of the servers from my friend and get a new media provider. When adding a new media import for the provider I can select between the available library sections. I'll try to look into `python-plexapi` to see if there are any other ways to get the library sections.

**Comment by Montellese** [comment]
Very odd. I just checked and PKC uses the same `/library/sections` endpoint to retrieve the available library sections:
* PKC: https://github.com/croneter/PlexKodiConnect/blob/27202d2ab2bfb7a32cd2d37eda869f0c6ebe2aac/resources/lib/plex_functions.py#L790
* python-plexapi: https://github.com/pkkid/python-plexapi/blob/master/plexapi/library.py#L40

**Comment by Montellese** [comment]
Is it possible that the type of the library section in Plex is configured as `video` / `Other videos` instead of `Movies` or `TV Shows`? Because `mediaimporter.plex` needs to know whether a video item is a movie or a tvshow to be able to properly import all the necessary metadata.

**Comment by rijsab** [comment]
I managed to get it syncing. However after completion I cannot see the movie/ TV show files. Usually this is pulled automatically by Kodi in Movies or TV show section. Am I missing something?

Thanks.

**Comment by Montellese** [comment]
How did you manage to select the library sections? Did you have to change something on the Plex server? This would be useful information for future users with similar issues.

You should automatically see all the imported movies in Kodi's `Movies` library and all tvshows in Kodi's `TV Shows` library. There is no integration in the `Videos -> Files` view though. If not could you please provide a (debug) log from your sync process?

**Comment by rijsab** [comment]
It was not clear to me when selecting library at the left to choose add Library sections.. I thought it will show in this section but I had to select. Nothing changed and something I have overlooked. 

The files are not showing up after syncing in Kodi.. Kodi is saying the library is empty.

Here is the log..

**Comment by Montellese** [comment]
Ah maybe we can improve the UI there a bit. Thanks for the input.

The link to the logs doesn't seem to work...

**Comment by rijsab** [comment]
I have updated the link.. should work now

**Comment by Montellese** [comment]
Both imports (movies and tvshows) failed after a few minutes because of a connection timeout to the server (either your internet connection was temporarily down or the server was temporarily unavailable). This is a know problem which I'm currently working on. https://github.com/Montellese/mediaimporter.plex/archive/refs/heads/improvement/retry_requests.zip adds the possibility to specify how often the import process should retry in case of connection problems. With this version a user on the Kodi forum managed to import over 180k episodes while it always failed with version 0.0.9. Maybe you can give it a try as well and report back.

**Comment by rijsab** [comment]
This version is working. All imported now, however I have noticed that many files are showing Playback failed. Is there anything I can do? Thanks.

**Comment by Montellese** [comment]
> This version is working. All imported now, however I have noticed that many files are showing Playback failed. Is there anything I can do? Thanks.

I will need a debug log from when you try to play some items which work and which fail to see what the issue might be.

**Comment by rijsab** [comment]
Here you go..

First file failed to play. Second file was working fine.

**Comment by Montellese** [comment]
Thanks for the debug log.

* The first file has the following URL: https://xxx/library/parts/154647/1615827657/file.mkv?X-Plex-Token=qpjnCz9xqMnxs9ap_fC_ and the server returns HTTP 503.
* The second file has the following URL: https://xxx/library/parts/5330/1476317480/file.mkv?X-Plex-Token=qpjnCz9xqMnxs9ap_fC and works fine.

Are you sure that playback for the first file works fine in Plex Web? The URLs look indentical (Apart from the IDs) so it's not like `mediaimporter.plex` has done something completely wrong during the import process.

**Comment by rijsab** [comment]
You are correct pal. The first line also not working on Plex server. HOWEVER I have checked a couple of other files which are 100% working on Plex but not on Kodi. I have noticed this is only happening to files with multiple versions (I.e. 4k & 1080p). Usually I get a notification which file to play, but with media importer this is not showing up. The addon works beside that really good and plays almost instantly compared to PlexKodiConnect.

**Comment by Montellese** [comment]
Thanks for the feedback. I didn't even know Plex support multiple versions for a movie / episode. I'll have to look into that. I'll create a separate issue for this and close this one.

**Comment by Montellese** [comment]
See #29.

**Comment by rijsab** [comment]
Great pal. Really appreciate the support on this and keep up the good work. You have made my life much easier now the play function is instantly. Would be great to have the multiple version option available in media I.porter 0.0.10 as this addon seems to sync larger libraries
