### ISSUE TITLE
Migrate to Python 3

### ISSUE THREAD

**Issue by Montellese** [Montellese/mediaimporter.plex#3]
The whole add-on needs to be migrated to Python 3 but it would be great if it would work for Python 2 and 3.

**Comment by Montellese** [comment]
I've created a `py3` branch with some initial changes, see https://github.com/Montellese/mediaimporter.plex/tree/py3.

**Comment by enen92** [comment]
If you could trigger a kodi py3 compatible build (OSX would be perfect) I can help you out porting the addon

**Comment by Montellese** [comment]
I've started a test-build for OSX and WIN64 at https://jenkins.kodi.tv/view/Automation/job/BuildMulti-Choice/329/. I'm currently stuck at https://github.com/Montellese/mediaimporter.plex/blob/py3/plexapi/compat.py#L61. I had to add that `proxydt` based on https://forum.kodi.tv/showthread.php?tid=112916&pid=2890924#pid2890924. But now I'm getting the following error:
```
TypeError: object.__init__() takes no arguments
```
but I don't understand why because `proxydt` derives from `datetime.datetime` and not from `object`.

**Comment by Montellese** [comment]
OK looks like I figured it out see d061503cc493f649cc0e3a815e936faf4e07a8a8 but I'm not sure if it is 100% correct and will also work with Python 2.

Here's the test build for OSX: http://mirrors.kodi.tv/test-builds/osx/x86_64/kodi-20200102-b294b07c-media_import_rebase_20200101-x86_64.dmg.

I managed to configure a media provider, add media imports and import items, so far so good.

**Comment by Montellese** [comment]
I've merged the `py3` branch into `master`.
