### ISSUE TITLE
Thumbs Episodes 

### ISSUE THREAD

**Issue by rijsab** [Montellese/mediaimporter.plex#30]

**Comment by Montellese** [comment]
Does this affect all thumbs? Or only the ones downloaded by a scraper or only the ones extracted from the actual episode?

**Comment by rijsab** [comment]
Hi,

Concerns all thumbs of the episodes. Are these scraped automatically by plex media importer?

**Comment by Montellese** [comment]
I just checked my setup with two different Plex servers and I can see episode thumbnails perfectly fine. Usually it takes a minute until all of them have been downloaded and cached when I first enter a specific tvshow / season folder but after that they appear instantly.

**Comment by kingkearney** [comment]
I can view the episode thumbnails when using the default skin but when I use any other skin the episode thumbnails don't show up.

Looks like your importing episode thumbnails from plex to kodi and naming them 'Poster' instead of 'Thumbnail'
