### ISSUE TITLE
Move websocket-client into script.module.websocket-client

### ISSUE THREAD

**Issue by Montellese** [Montellese/mediaimporter.plex#5]
Since both `mediaimporter.plex` and `mediaimporter.emby` use the `websocket-client` we should probably move it to a separate `script.module.websocket-client` add-on. We have to be careful to choose a version which supports both Python 2 and 3 and is compatible with `python-plexapi`.

**Comment by enen92** [comment]
I think I'll try to come up with an idea for a (totally unrelated to mediaimport) addon that requires a websocket connection to show some notifications in kodi. That way I can submit the script.module to Matrix and we avoid the creation of an external repository. If media importer doesn't make it into Kodi in the future I'll just mark my addon as broken and remove the dependency.

**Comment by Montellese** [comment]
Wouldn't having a repository make it easier for others to update the media importer add-ons?

**Comment by enen92** [comment]
Sure. I was just trying to avoid creating even more work for you and thought the only reason was the script module.
We can use github to set up a repository. I'd suggest you to create a new project/repository in your account called for instance `repository.mediaimport`. If you can add me as a collaborator to that project I can set it up and save you from the hassle of having yet more work

**Comment by enen92** [comment]
To start things over I'll create the `script.module.websocket-client` and play a bit with mediaimporter.plex to make it work with the module without any patch on the original module. When this is done I'll transfer the ownership of the `script.module.websocket-client` and I'll send a PR against this repo.

**Comment by Montellese** [comment]
I've setup a repository at https://github.com/Montellese/repository.mediaimport and tried my luck at generating the whole repository. No idea if I did it right but I was able to install the repository from ZIP in code and I can browse to the two media importer add-ons.

**Comment by Montellese** [comment]
Could you also uncomment https://github.com/Montellese/mediaimporter.plex/blob/master/plexapi/alert.py#L4 ? I just remembered that I commented this out. I don't need `plexapi.alert` but better stick to upstream as close as possible.

**Comment by enen92** [comment]
Have you made any changes to `plexapi` besides the websocket? If not maybe plexapi should be made into a script.module as well

**Comment by Montellese** [comment]
Here's the OSX test build for the (old) Pyton 2 based version: http://mirrors.kodi.tv/test-builds/osx/x86_64/kodi-20200101-ebfd5e43-media_import_rebase_20191003-x86_64.dmg

Concerning `python-plexapi` I had to make some changes, see https://github.com/Montellese/python-plexapi/commits/kodi and https://github.com/Montellese/python-plexapi/commit/ca16297498ba0f8549668274f1b57a86c1c4bd7f. The top commit in the `kodi` branch is not up to date.

**Comment by Montellese** [comment]
Closing this as #7 has been merged.
